# Generated by Django 3.2.5 on 2021-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bayi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bayi', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('umur', models.IntegerField()),
                ('berat_badan', models.FloatField()),
                ('tinggi_badan', models.FloatField()),
            ],
            options={
                'db_table': 'bayis',
            },
        ),
    ]
